[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
socialnetwork_rs = "HJ52iVx4M1A29841eXbT2SCUo1Gfcho7AzFPjGH24sys"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/crab/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
migrate = "yarn run ts-node -p ./tsconfig.json -t 1000000 migrations/**/*.ts"